version: '3'
services:
  sadlwebexp:
    build:
      context: .
      dockerfile: Dockerfile-experimental
    # entrypoint: /bin/bash
    # command: "yarn theia start /home/project --hostname=0.0.0.0"
    volumes:
      - ../SADL/:/root/SADL/
      - ./theia_recs/.project:/root/SADL/.project
      - ./theia_recs/settings.json:/root/SADL/settings.json
    ports:
      - "3000:3000"
